/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/components/**/*.{js,vue,ts}",
    "./app/layouts/**/*.vue",
    "./app/pages/**/*.vue",
    "./app/plugins/**/*.{js,ts}",
    "./app/app.vue",
    "./app/error.vue",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-dim": "#d73357",
        "tertiary-fixed": "#ffbf00",
        "surface-bright": "#282b3a",
        "on-tertiary-container": "#563e00",
        "tertiary-fixed-dim": "#eeb200",
        "on-primary-fixed": "#000000",
        "outline-variant": "#464752",
        primary: "#95aaff",
        "on-secondary-fixed-variant": "#006a34",
        "on-secondary-container": "#e3ffe4",
        background: "#0c0e17",
        "secondary-fixed": "#83fba5",
        "surface-tint": "#95aaff",
        "on-secondary-fixed": "#004a22",
        "on-surface-variant": "#aaaab7",
        "on-primary": "#00247e",
        "on-error": "#490013",
        "primary-fixed-dim": "#6e8cff",
        "secondary-container": "#006d36",
        "inverse-on-surface": "#53545f",
        "error-container": "#a70138",
        "on-secondary": "#005f2e",
        "surface-container-highest": "#222532",
        "secondary-dim": "#75ec98",
        "on-background": "#f0f0fd",
        "on-primary-container": "#001a63",
        "tertiary-container": "#ffbf00",
        "surface-container": "#171924",
        "on-tertiary-fixed": "#3d2b00",
        "inverse-primary": "#004cef",
        "primary-container": "#829bff",
        surface: "#0c0e17",
        "primary-dim": "#3766ff",
        "surface-variant": "#222532",
        "on-tertiary": "#614700",
        "surface-dim": "#0c0e17",
        "inverse-surface": "#faf8ff",
        "on-tertiary-fixed-variant": "#614700",
        "surface-container-low": "#11131d",
        tertiary: "#ffd16f",
        "tertiary-dim": "#eeb200",
        "on-primary-fixed-variant": "#002278",
        "surface-container-high": "#1c1f2b",
        secondary: "#83fba5",
        "on-surface": "#f0f0fd",
        "secondary-dim": "#75ec98",
        "primary-fixed": "#829bff",
        error: "#ff6e84",
        outline: "#737580",
        "on-error-container": "#ffb2b9",
        "surface-container-lowest": "#000000",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
